# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dr. Xiao Shiliang's Homepage
tagline:          ''
description:      Pleasure is learning and being able to practice often what one has learned. \n Happiness is having old friends coming from far away ------- by Confucius 
url:              http://slxiao.github.io
baseurl:          /

author:
  name:           'Shiliang Xiao'
  url:            https://slxiao.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/slxiao/slxiao.github.io
