# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shelwin Xiao's Blog |公众号'测试不将就'
email: shliang.xiao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Pleasure is learning and being able to practice often-times what one has learned. Happiness is having old friends coming from far away---by Confucius, ~500 B.C.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://slxiao.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  slxiao

# Build settings
markdown: kramdown
kramwdown:
      parse_block_html: true
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
