# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Xiao Shiliang's Homepage
tagline:          ''
description:      'This is the homepage of Dr. Shiliang Xiao'
url:              http://slxiao.github.io
baseurl:          /

author:
  name:           'Shiliang Xiao'
  url:            https://slxiao.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/slxiao/slxiao.github.io
